spring:
  cloud:
    discovery:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka
    config:
      uri: http://localhost:8888
      fail-fast: true
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka