apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-service-sa
  namespace: ecommerce

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ecommerce
  name: product-service-role
rules:
  - apiGroups: [""]
    resources: ["pods", "endpoints", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ecommerce
  name: product-service-rolebinding
subjects:
  - kind: ServiceAccount
    name: product-service-sa
    namespace: ecommerce
roleRef:
  kind: Role
  name: product-service-role
  apiGroup: rbac.authorization.k8s.io