apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      restartPolicy: Always
      containers:
        - name: api-gateway
          image: 192.168.1.170:5000/ecommerce/api-gateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: JWT_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: JWT_SECRET_KEY
            - name: JWT_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: JWT_EXPIRATION
            - name: SPRING_CLOUD_DISCOVERY_CLIENT_SERVICE-URL_DEFAULTZONE
              value: "http://service-discovery:8761/eureka"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10