apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: 192.168.1.170:5000/ecommerce/config-server:latest
          ports:
            - containerPort: 8888
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: github.token