apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-ingress
  namespace: ecommerce
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: service.pallav.ind.in
      http:
        paths:
          # Path for the frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ecommerce-frontend-service
                port:
                  number: 80
          # Path for the API Gateway
          - path: /gateway
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080
          # Path for the Service Discovery
          - path: /discovery
            pathType: Prefix
            backend:
              service:
                name: service-discovery
                port:
                  number: 8761