apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      restartPolicy: Always
      serviceAccountName: user-service-sa
      containers:
        - name: user-service
          image: 192.168.1.170:5000/ecommerce/user-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: JWT_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: JWT_SECRET_KEY
            - name: JWT_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: JWT_EXPIRATION