spring:
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<segment>.*), /api/users/$\{segment}
            - AuthenticationFilter
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
          filters:
            - RewritePath=/products/(?<segment>.*), /$\{segment}
            - AuthenticationFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter
    config:
      uri: http://localhost:8888
      fail-fast: true
  config:
    import: configserver:http://localhost:8888
logging:
  file:
    name: api-gateway.log
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway