spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
          filters:
            - RewritePath=/products/(?<segment>.*), /$\{segment}
    config:
      uri: http://localhost:8888
      fail-fast: true
  config:
    import: configserver:http://localhost:8888
logging:
  file:
    name: api-gateway.log

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway