spring:
  cloud:
    gateway:
      locator:
        enabled: true
    config:
      uri: http://localhost:8888
      fail-fast: true
  config:
    import: configserver:http://localhost:8888
logging:
  file:
    name: api-gateway.log

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway