apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: ecommerce
  labels:
    app: cassandra
spec:
  clusterIP: None
  ports:
    - port: 9042
      name: cql
  selector:
    app: cassandra
