apiVersion: v1
kind: ServiceAccount
metadata:
  name: cassandra-sa
  namespace: ecommerce

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cassandra-role
  namespace: ecommerce
rules:
  - apiGroups: [""]
    resources: ["pods", "endpoints", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cassandra-rolebinding
  namespace: ecommerce
subjects:
  - kind: ServiceAccount
    name: cassandra-sa
    namespace: ecommerce
roleRef:
  kind: Role
  name: cassandra-role
  apiGroup: rbac.authorization.k8s.io
