apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  namespace: ecommerce
spec:
  serviceName: cassandra
  replicas: 3
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      serviceAccountName: cassandra-sa
      containers:
        - name: cassandra
          image: cassandra:4.0
          ports:
            - containerPort: 9042
              name: cql
          env:
            - name: CASSANDRA_CLUSTER_NAME
              value: ecommerce-cluster
            - name: CASSANDRA_SEEDS
              value: cassandra-0.cassandra.ecommerce.svc.cluster.local
            - name: CASSANDRA_DC
              value: datacenter1
            - name: CASSANDRA_RACK
              value: rack1
            - name: CASSANDRA_ENDPOINT_SNITCH
              value: GossipingPropertyFileSnitch
            - name: CASSANDRA_NUM_TOKENS
              value: "256"
          volumeMounts:
            - name: cassandra-data
              mountPath: /var/lib/cassandra
  volumeClaimTemplates:
    - metadata:
        name: cassandra-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
