apiVersion: v1
kind: Service
metadata:
  name: cassandra-cluster
  namespace: ecommerce
  labels:
    app: cassandra
spec:
  type: ClusterIP
  ports:
    - port: 9042
      targetPort: 9042
      protocol: TCP
      name: cql
  selector:
    app: cassandra
