name: API Gateway CI/CD

on:
  push:
    paths:
      - 'services/api-gateway/**'
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build shared lib with Maven
        working-directory: shared-libraries
        run: mvn clean install

      - name: Build api-gateway with Maven
        working-directory: services/api-gateway
        run: mvn clean install