name: Cart Service CI/CD

on:
  push:
    paths:
      - 'services/cart-service/**'
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        working-directory: services/cart-service
        run: mvn clean install